# Generated by Django 4.1 on 2022-08-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbmail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
