# Generated by Django 4.1 on 2022-08-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image_product_thumbmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbmail',
            new_name='thumbnail',
        ),
    ]
